// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqettcemsqhtzgqhjvos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZXR0Y2Vtc3FodHpncWhqdm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTkzMzgsImV4cCI6MjA1ODY5NTMzOH0.Q5XoIq1ynanOvmr7sVPZkzRP42tl_bYt4jPk6lB-KjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);